// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhipRadio.Infrastructure.Persistence;

#nullable disable

namespace WhipRadio.Infrastructure.Migrations
{
    [DbContext(typeof(RadioDbContext))]
    [Migration("20260620124444_Phase3cSpecialistProduction")]
    partial class Phase3cSpecialistProduction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WhipRadio.Core.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RelatedTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoicedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasPlayed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("WasPlayed");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Biography")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeepBackgroundBiography")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleDescriptor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ArtistMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceCreationPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "SortOrder");

                    b.ToTable("ArtistMembers");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownVotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TalkDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("TalkDepth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Talkativeness")
                        .HasColumnType("REAL");

                    b.Property<int>("UpVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Jingle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUsed")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.ToTable("Jingles");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ListenerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DismissalReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FulfilledByTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestGenre")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMood")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ListenerMessages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.MediaAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalyzerVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeatGridJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<double>("BpmConfidence")
                        .HasColumnType("REAL");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("EnergyProfileJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("IntegratedLufs")
                        .HasColumnType("REAL");

                    b.Property<double>("IntroConfidence")
                        .HasColumnType("REAL");

                    b.Property<double?>("IntroEndSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LeadingSilenceSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("OutroConfidence")
                        .HasColumnType("REAL");

                    b.Property<double?>("OutroStartSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("TrailingSilenceSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("TruePeakDb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ItemType", "ItemId")
                        .IsUnique();

                    b.ToTable("MediaAnalyses");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedTalkPartKinds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineEnergy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineFormality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineHumorLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineTalkativeness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineWarmth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EvergreenBitTolerance")
                        .HasColumnType("REAL");

                    b.Property<int>("ExactReplayTolerance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNewsSpecialist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeatherSpecialist")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTalkPartsPerBreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTalkPartsPerBreak")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredGenres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PrefersVocals")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpeechRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TalkBreakFrequencyTracks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Talkativeness")
                        .HasColumnType("REAL");

                    b.Property<string>("TtsEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ModeratorMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId", "Layer", "Date");

                    b.ToTable("ModeratorMemories");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPolledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxItemsPerPoll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollCadenceMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "LastPolledAtUtc");

                    b.ToTable("NewsFeeds");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedSummary")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProducedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FeedId", "Url")
                        .IsUnique();

                    b.HasIndex("Status", "PublishedAtUtc", "FirstSeenAtUtc");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProducedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TargetUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("Kind", "TargetUtc")
                        .IsUnique();

                    b.HasIndex("Status", "TargetUtc");

                    b.ToTable("NewsPackages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.PlayLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.ToTable("PlayLog");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FormatId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("DayOfWeek", "StartMinute")
                        .IsUnique();

                    b.ToTable("ProgramSlots");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnalysisRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnouncementEveryNTracks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BeatAlignBpmTolerancePct")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultCrossfadeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMusicProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DuckLevelDb")
                        .HasColumnType("REAL");

                    b.Property<int>("DuckRampMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElevenLabsApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ElevenLabsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableBreathMarkers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FrequencyMhz")
                        .HasColumnType("REAL");

                    b.Property<bool>("GreetingsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardCutGapAfterTalkMsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardCutGapAfterTalkMsMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardCutGapSongMsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardCutGapSongMsMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLibrarySize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxMakeupGainDb")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxPendingGreetings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTrackDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTrackDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MixerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MusicProductionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewsCategoryOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NewsExtractionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsPackageCadenceMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsPackageMaxDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NewsPresenterModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NewsSeedFeedsCreated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenAiApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlayoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostHitSafetyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationMission")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StationSlogan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StationVision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyWeightsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetLufs")
                        .HasColumnType("REAL");

                    b.Property<int>("TargetQueueLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TopOfHourFadeOutSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("TopOfHourIntroGraceSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeatherCadenceMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WeatherEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WeatherFullHandoverEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeatherLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("WeatherLocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeatherLongitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("WeatherSpecialistModeratorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StationSettings");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "IsActive");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StudioHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudioKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.HasIndex("StudioId", "StartedAtUtc");

                    b.HasIndex("StudioKind", "StartedAtUtc");

                    b.ToTable("StudioHistory");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CooldownDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExactReplayCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreshRetellCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Premise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetirementReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastUsedAtUtc");

                    b.HasIndex("ModeratorId", "Status");

                    b.ToTable("TalkBits");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBitRendition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedFromRetelling")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TalkBitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TalkBitId");

                    b.ToTable("TalkBitRenditions");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RenderedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetWindowEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetWindowStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("TalkBreaks");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DesiredDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JingleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedTrackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TalkBitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TalkBreakId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetWindowEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetWindowStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WordBudget")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("TalkBreakId", "SortOrder")
                        .IsUnique();

                    b.ToTable("TalkParts");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownVotes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVocals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lyrics")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongStory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Genre");

                    b.HasIndex("IsRetired");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TransitionLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClipCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GapMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IncomingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncomingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutgoingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutgoingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OverlapSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("TransitionLog");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientHint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Announcement", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ArtistMember", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Artist", "Artist")
                        .WithMany("Members")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Format", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsItem", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.NewsFeed", "Feed")
                        .WithMany("Items")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsPackage", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Announcement", null)
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramSlot", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StudioHistoryEntry", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBitRendition", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.TalkBit", "TalkBit")
                        .WithMany("Renditions")
                        .HasForeignKey("TalkBitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalkBit");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkPart", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.TalkBreak", "TalkBreak")
                        .WithMany("Parts")
                        .HasForeignKey("TalkBreakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalkBreak");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Track", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Vote", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Artist", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsFeed", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBit", b =>
                {
                    b.Navigation("Renditions");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBreak", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
