using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WhipRadio.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Phase2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ScheduleSlots");

            migrationBuilder.AddColumn<Guid>(
                name: "ArtistId",
                table: "Tracks",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Subgenre",
                table: "Tracks",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ElevenLabsApiKey",
                table: "StationSettings",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "ElevenLabsEnabled",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "EnableBreathMarkers",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "FirstDayOfWeek",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<double>(
                name: "FrequencyMhz",
                table: "StationSettings",
                type: "REAL",
                nullable: false,
                defaultValue: 0.0);

            migrationBuilder.AddColumn<int>(
                name: "MaxLibrarySize",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "MaxTrackDurationSeconds",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "MinTrackDurationSeconds",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "MusicProductionEnabled",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "OpenAiApiKey",
                table: "StationSettings",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "OpenAiModel",
                table: "StationSettings",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "PlayoutEnabled",
                table: "StationSettings",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "TextProvider",
                table: "StationSettings",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<double>(
                name: "DurationSeconds",
                table: "PlayLog",
                type: "REAL",
                nullable: false,
                defaultValue: 0.0);

            migrationBuilder.AddColumn<string>(
                name: "Gender",
                table: "Moderators",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Moderators",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "TtsEngine",
                table: "Moderators",
                type: "TEXT",
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateTable(
                name: "Artists",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Genre = table.Column<string>(type: "TEXT", nullable: false),
                    Subgenre = table.Column<string>(type: "TEXT", nullable: false),
                    StyleDescriptor = table.Column<string>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    IsRetired = table.Column<bool>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Artists", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Formats",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Description = table.Column<string>(type: "TEXT", nullable: false),
                    Genre = table.Column<string>(type: "TEXT", nullable: false),
                    Subgenre = table.Column<string>(type: "TEXT", nullable: false),
                    ModeratorId = table.Column<int>(type: "INTEGER", nullable: true),
                    Reason = table.Column<string>(type: "TEXT", nullable: false),
                    IsEnabled = table.Column<bool>(type: "INTEGER", nullable: false),
                    UpVotes = table.Column<int>(type: "INTEGER", nullable: false),
                    DownVotes = table.Column<int>(type: "INTEGER", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Formats", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Formats_Moderators_ModeratorId",
                        column: x => x.ModeratorId,
                        principalTable: "Moderators",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "ModeratorMemories",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ModeratorId = table.Column<int>(type: "INTEGER", nullable: false),
                    Date = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    Content = table.Column<string>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ModeratorMemories", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ProgramSlots",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    DayOfWeek = table.Column<int>(type: "INTEGER", nullable: false),
                    StartMinute = table.Column<int>(type: "INTEGER", nullable: false),
                    DurationMinutes = table.Column<int>(type: "INTEGER", nullable: false),
                    FormatId = table.Column<Guid>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProgramSlots", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ProgramSlots_Formats_FormatId",
                        column: x => x.FormatId,
                        principalTable: "Formats",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Tracks_ArtistId",
                table: "Tracks",
                column: "ArtistId");

            migrationBuilder.CreateIndex(
                name: "IX_Artists_Genre",
                table: "Artists",
                column: "Genre");

            migrationBuilder.CreateIndex(
                name: "IX_Artists_Name",
                table: "Artists",
                column: "Name");

            migrationBuilder.CreateIndex(
                name: "IX_Formats_ModeratorId",
                table: "Formats",
                column: "ModeratorId");

            migrationBuilder.CreateIndex(
                name: "IX_ModeratorMemories_ModeratorId_Date",
                table: "ModeratorMemories",
                columns: new[] { "ModeratorId", "Date" });

            migrationBuilder.CreateIndex(
                name: "IX_ProgramSlots_DayOfWeek_StartMinute",
                table: "ProgramSlots",
                columns: new[] { "DayOfWeek", "StartMinute" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ProgramSlots_FormatId",
                table: "ProgramSlots",
                column: "FormatId");

            migrationBuilder.AddForeignKey(
                name: "FK_Tracks_Artists_ArtistId",
                table: "Tracks",
                column: "ArtistId",
                principalTable: "Artists",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Tracks_Artists_ArtistId",
                table: "Tracks");

            migrationBuilder.DropTable(
                name: "Artists");

            migrationBuilder.DropTable(
                name: "ModeratorMemories");

            migrationBuilder.DropTable(
                name: "ProgramSlots");

            migrationBuilder.DropTable(
                name: "Formats");

            migrationBuilder.DropIndex(
                name: "IX_Tracks_ArtistId",
                table: "Tracks");

            migrationBuilder.DropColumn(
                name: "ArtistId",
                table: "Tracks");

            migrationBuilder.DropColumn(
                name: "Subgenre",
                table: "Tracks");

            migrationBuilder.DropColumn(
                name: "ElevenLabsApiKey",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "ElevenLabsEnabled",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "EnableBreathMarkers",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "FirstDayOfWeek",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "FrequencyMhz",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "MaxLibrarySize",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "MaxTrackDurationSeconds",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "MinTrackDurationSeconds",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "MusicProductionEnabled",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "OpenAiApiKey",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "OpenAiModel",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "PlayoutEnabled",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "TextProvider",
                table: "StationSettings");

            migrationBuilder.DropColumn(
                name: "DurationSeconds",
                table: "PlayLog");

            migrationBuilder.DropColumn(
                name: "Gender",
                table: "Moderators");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Moderators");

            migrationBuilder.DropColumn(
                name: "TtsEngine",
                table: "Moderators");

            migrationBuilder.CreateTable(
                name: "ScheduleSlots",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    ModeratorId = table.Column<int>(type: "INTEGER", nullable: false),
                    Genre = table.Column<string>(type: "TEXT", nullable: false),
                    HourOfDay = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ScheduleSlots", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ScheduleSlots_Moderators_ModeratorId",
                        column: x => x.ModeratorId,
                        principalTable: "Moderators",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ScheduleSlots_HourOfDay",
                table: "ScheduleSlots",
                column: "HourOfDay",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_ScheduleSlots_ModeratorId",
                table: "ScheduleSlots",
                column: "ModeratorId");
        }
    }
}
