// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhipRadio.Infrastructure.Persistence;

#nullable disable

namespace WhipRadio.Infrastructure.Migrations
{
    [DbContext(typeof(RadioDbContext))]
    [Migration("20260611020603_Phase2RequestFulfillmentAndDefaultMusicProvider")]
    partial class Phase2RequestFulfillmentAndDefaultMusicProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WhipRadio.Core.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RelatedTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoicedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasPlayed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("WasPlayed");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StyleDescriptor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownVotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Talkativeness")
                        .HasColumnType("REAL");

                    b.Property<int>("UpVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ListenerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DismissalReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FulfilledByTrackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestGenre")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMood")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ListenerMessages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonaPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredGenres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PrefersVocals")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SpeechRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Talkativeness")
                        .HasColumnType("REAL");

                    b.Property<string>("TtsEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ModeratorMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId", "Date");

                    b.ToTable("ModeratorMemories");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.PlayLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.ToTable("PlayLog");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FormatId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("DayOfWeek", "StartMinute")
                        .IsUnique();

                    b.ToTable("ProgramSlots");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnouncementEveryNTracks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultMusicProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElevenLabsApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ElevenLabsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableBreathMarkers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FrequencyMhz")
                        .HasColumnType("REAL");

                    b.Property<bool>("GreetingsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLibrarySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPendingGreetings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTrackDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTrackDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MusicProductionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenAiApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlayoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetQueueLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StationSettings");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownVotes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVocals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lyrics")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Genre");

                    b.HasIndex("IsRetired");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientHint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Announcement", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Format", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramSlot", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Track", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Vote", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });
#pragma warning restore 612, 618
        }
    }
}
