// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WhipRadio.Infrastructure.Persistence;

#nullable disable

namespace WhipRadio.Infrastructure.Migrations
{
    [DbContext(typeof(RadioDbContext))]
    partial class RadioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WhipRadio.Core.Entities.AgentActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tool")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("AgentName", "CreatedAtUtc");

                    b.ToTable("AgentActionLogs");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayoutIntent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Immediate");

                    b.Property<Guid?>("RelatedTrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScriptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoicedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasPlayed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("PlayoutIntent");

                    b.HasIndex("WasPlayed");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreationHint")
                        .HasColumnType("text");

                    b.Property<string>("DeepBackgroundBiography")
                        .HasColumnType("text");

                    b.Property<int?>("FormationYear")
                        .HasColumnType("integer");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<string>("PromotionText")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StyleDescriptor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ArtistMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TtsEngine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("qwen");

                    b.Property<string>("VoiceCreationPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoiceDesignLastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoiceDesignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoiceId")
                        .HasColumnType("text");

                    b.Property<string>("VoiceReferencePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId", "SortOrder");

                    b.ToTable("ArtistMembers");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ArtistPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending();

                    b.HasIndex("TrackId");

                    b.ToTable("ArtistPosts");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AdminLastReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CounterpartModeratorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartModeratorId");

                    b.HasIndex("LastMessageAtUtc");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("Kind", "ModeratorId", "CounterpartModeratorId");

                    b.ToTable("ChatChannels");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatChannelMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtistMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtistMemberId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("GuestId");

                    b.HasIndex("ModeratorId");

                    b.ToTable("ChatChannelMembers");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HopCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SenderArtistMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SenderGuestId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SenderModeratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("SenderArtistMemberId");

                    b.HasIndex("SenderGuestId");

                    b.HasIndex("SenderModeratorId");

                    b.HasIndex("ChannelId", "CreatedAtUtc");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ConversationSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChaptersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DegradationReason")
                        .HasColumnType("text");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("text");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PodcastShowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProducedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductionState")
                        .HasColumnType("text");

                    b.Property<string>("ReferencedTrackIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StepTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TargetUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.Property<string>("TurnsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetUtc");

                    b.HasIndex("PodcastShowId", "TargetUtc");

                    b.ToTable("ConversationSegments");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DownVotes")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TalkDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("TalkDepth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Talkativeness")
                        .HasColumnType("double precision");

                    b.Property<int>("UpVotes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreationHint")
                        .HasColumnType("text");

                    b.Property<string>("DeepBackground")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("text");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TtsEngine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("qwen");

                    b.Property<string>("VoiceCreationPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoiceDesignLastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoiceDesignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoiceFx")
                        .HasColumnType("text");

                    b.Property<string>("VoiceId")
                        .HasColumnType("text");

                    b.Property<string>("VoiceReferencePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Jingle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("StationId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelUsed")
                        .HasColumnType("text");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeedUsed")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsActive");

                    b.ToTable("Jingles");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ListenerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<string>("DismissalReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("FulfilledByTrackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestGenre")
                        .HasColumnType("text");

                    b.Property<string>("RequestMood")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ListenerMessages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.MediaAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AnalyzerVersion")
                        .HasColumnType("integer");

                    b.Property<string>("BeatGridJson")
                        .HasColumnType("text");

                    b.Property<double?>("Bpm")
                        .HasColumnType("double precision");

                    b.Property<double>("BpmConfidence")
                        .HasColumnType("double precision");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("EnergyProfileJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("IntegratedLufs")
                        .HasColumnType("double precision");

                    b.Property<double>("IntroConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("IntroEndSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LeadingSilenceSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("OutroConfidence")
                        .HasColumnType("double precision");

                    b.Property<double?>("OutroStartSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("TrailingSilenceSeconds")
                        .HasColumnType("double precision");

                    b.Property<double>("TruePeakDb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItemType", "ItemId")
                        .IsUnique();

                    b.ToTable("MediaAnalyses");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Metadata.ExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.HasIndex("Source", "Value");

                    b.ToTable("ExternalIds");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Metadata.KnowledgeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LicenseClass")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Source", "SourceEntityId")
                        .IsUnique();

                    b.ToTable("KnowledgeEntries");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Metadata.MetadataCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistEntityId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayAlbum")
                        .HasColumnType("text");

                    b.Property<string>("DisplayArtist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DisplayYear")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("MetadataCandidates");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Metadata.MetadataClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean");

                    b.Property<int>("LicenseClass")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceEntityId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("MetadataClaims");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Moderator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedTalkPartKinds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaselineEnergy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaselineFormality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaselineHumorLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaselineTalkativeness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaselineWarmth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EvergreenBitTolerance")
                        .HasColumnType("double precision");

                    b.Property<int>("ExactReplayTolerance")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewsSpecialist")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWeatherSpecialist")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxTalkPartsPerBreak")
                        .HasColumnType("integer");

                    b.Property<int>("MinTalkPartsPerBreak")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonaPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PreferredGenres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("PrefersVocals")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SpeechRate")
                        .HasColumnType("double precision");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TalkBreakFrequencyTracks")
                        .HasColumnType("integer");

                    b.Property<double>("Talkativeness")
                        .HasColumnType("double precision");

                    b.Property<string>("TtsEngine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VoiceDescription")
                        .HasColumnType("text");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ModeratorMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId", "Layer", "Date");

                    b.ToTable("ModeratorMemories");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxItemsPerPoll")
                        .HasColumnType("integer");

                    b.Property<int>("PollCadenceMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "LastPolledAtUtc");

                    b.ToTable("NewsFeeds");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProducedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FeedId", "Url")
                        .IsUnique();

                    b.HasIndex("Status", "PublishedAtUtc", "FirstSeenAtUtc");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProducedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProducedSegmentsJson")
                        .HasColumnType("text");

                    b.Property<string>("ProductionState")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSummary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StepTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TargetUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("Kind", "TargetUtc")
                        .IsUnique();

                    b.HasIndex("Status", "TargetUtc");

                    b.ToTable("NewsPackages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ParticipantMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParticipantKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantKey");

                    b.ToTable("ParticipantMemories");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.PlayLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasFallback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("ItemType", "PlayedAt");

                    b.ToTable("PlayLog");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.PodcastShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("IsEnabled");

                    b.ToTable("PodcastShows");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramDirectorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Source", "CreatedAtUtc");

                    b.ToTable("ProgramDirectorLogs");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FormatId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("DayOfWeek", "StartMinute")
                        .IsUnique();

                    b.ToTable("ProgramSlots");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnalysisRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("AnnouncementEveryNTracks")
                        .HasColumnType("integer");

                    b.Property<bool>("ArchiveEnrichmentEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArchivePlayoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArchiveUploadEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("BeatAlignBpmTolerancePct")
                        .HasColumnType("double precision");

                    b.Property<int>("ChatHistoryPromptMessages")
                        .HasColumnType("integer");

                    b.Property<int>("ChatMaxAgentHops")
                        .HasColumnType("integer");

                    b.Property<int>("ChatRetainedMessagesPerChannel")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultArtistLookbackTracks")
                        .HasColumnType("integer");

                    b.Property<double>("DefaultCrossfadeSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultMaxArtistPlaysPerHour")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultMusicProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DuckLevelDb")
                        .HasColumnType("double precision");

                    b.Property<int>("DuckRampMs")
                        .HasColumnType("integer");

                    b.Property<string>("ElevenLabsApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ElevenLabsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableBreathMarkers")
                        .HasColumnType("boolean");

                    b.Property<double>("FatigueFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("FirstDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<double>("FrequencyMhz")
                        .HasColumnType("double precision");

                    b.Property<bool>("GreetingsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("HardCutGapAfterTalkMsMax")
                        .HasColumnType("integer");

                    b.Property<int>("HardCutGapAfterTalkMsMin")
                        .HasColumnType("integer");

                    b.Property<int>("HardCutGapSongMsMax")
                        .HasColumnType("integer");

                    b.Property<int>("HardCutGapSongMsMin")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLibrarySize")
                        .HasColumnType("integer");

                    b.Property<double>("MaxMakeupGainDb")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxPendingGreetings")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTrackDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("MinTrackDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("MixerEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("MusicProductionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NewsCategoryOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NewsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("NewsExtractionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NewsLongFormatAirTimes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewsLongFormatDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("NewsLongFormatEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("NewsPackageCadenceMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("NewsPackageMaxDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("NewsPresenterModeratorId")
                        .HasColumnType("integer");

                    b.Property<bool>("NewsSeedFeedsCreated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NewsShowFormatId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpenAiApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PlayoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PodcastKnowledgeEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PostHitSafetyMs")
                        .HasColumnType("integer");

                    b.Property<int>("RecentExclusionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("SelectionDiversityEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("StationMission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationSlogan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationVision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyWeightsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TargetLufs")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetQueueLength")
                        .HasColumnType("integer");

                    b.Property<string>("TextProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TopOfHourFadeOutSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("TopOfHourIntroGraceSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherCadenceMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("WeatherEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeatherFullHandoverEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("WeatherLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("WeatherLocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WeatherLongitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("WeatherSpecialistModeratorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StationSettings");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JobsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("JobsFailed")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "IsActive");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StudioHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudioKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudioName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.HasIndex("StudioId", "StartedAtUtc");

                    b.HasIndex("StudioKind", "StartedAtUtc");

                    b.ToTable("StudioHistory");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CooldownDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExactReplayCount")
                        .HasColumnType("integer");

                    b.Property<int>("FreshRetellCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<string>("Premise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetirementReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastUsedAtUtc");

                    b.HasIndex("ModeratorId", "Status");

                    b.ToTable("TalkBits");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBitRendition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CreatedFromRetelling")
                        .HasColumnType("boolean");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastPlayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TalkBitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TalkBitId");

                    b.ToTable("TalkBitRenditions");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeratorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RenderedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetWindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TargetWindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("TalkBreaks");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DesiredDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JingleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedTrackId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TalkBitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TalkBreakId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TargetWindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TargetWindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WordBudget")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("TalkBreakId", "SortOrder")
                        .IsUnique();

                    b.ToTable("TalkParts");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownVotes")
                        .HasColumnType("integer");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FileHash")
                        .HasColumnType("text");

                    b.Property<bool>("FileMissing")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FileModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("GenerationPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasVocals")
                        .HasColumnType("boolean");

                    b.Property<string>("ImportedAlbum")
                        .HasColumnType("text");

                    b.Property<string>("ImportedArtist")
                        .HasColumnType("text");

                    b.Property<int?>("ImportedYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastEnrichmentAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lyrics")
                        .HasColumnType("text");

                    b.Property<double?>("MetadataConfidence")
                        .HasColumnType("double precision");

                    b.Property<int>("MetadataStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<string>("SongStory")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subgenre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpVotes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("FileHash");

                    b.HasIndex("Genre");

                    b.HasIndex("IsRetired");

                    b.HasIndex("Source");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TransitionLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClipCount")
                        .HasColumnType("integer");

                    b.Property<int>("GapMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("IncomingId")
                        .HasColumnType("uuid");

                    b.Property<string>("IncomingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OutgoingId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutgoingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OverlapSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("TransitionLog");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientHint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Announcement", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ArtistMember", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Artist", "Artist")
                        .WithMany("Members")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ArtistPost", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhipRadio.Core.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatChannel", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "CounterpartModerator")
                        .WithMany()
                        .HasForeignKey("CounterpartModeratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CounterpartModerator");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatChannelMember", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.ArtistMember", "ArtistMember")
                        .WithMany()
                        .HasForeignKey("ArtistMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WhipRadio.Core.Entities.ChatChannel", "Channel")
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhipRadio.Core.Entities.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ArtistMember");

                    b.Navigation("Channel");

                    b.Navigation("Guest");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.ChatChannel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhipRadio.Core.Entities.ArtistMember", "SenderArtistMember")
                        .WithMany()
                        .HasForeignKey("SenderArtistMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WhipRadio.Core.Entities.Guest", "SenderGuest")
                        .WithMany()
                        .HasForeignKey("SenderGuestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WhipRadio.Core.Entities.Moderator", "SenderModerator")
                        .WithMany()
                        .HasForeignKey("SenderModeratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("SenderArtistMember");

                    b.Navigation("SenderGuest");

                    b.Navigation("SenderModerator");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ConversationSegment", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Announcement", null)
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WhipRadio.Core.Entities.PodcastShow", null)
                        .WithMany()
                        .HasForeignKey("PodcastShowId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Format", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Moderator", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId");

                    b.OwnsOne("WhipRadio.Core.Selection.FormatSelectionRules", "SelectionRules", b1 =>
                        {
                            b1.Property<Guid>("FormatId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ArtistLookbackTracks")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(8);

                            b1.Property<double?>("BpmTolerancePct")
                                .HasColumnType("double precision");

                            b1.Property<Guid?>("FeaturedArtistId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxArtistPlaysPerHour")
                                .HasColumnType("integer");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("StandardRotation");

                            b1.Property<bool>("PreferHostGenres")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true);

                            b1.Property<bool>("SubgenreRotation")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true);

                            b1.Property<double?>("TargetBpm")
                                .HasColumnType("double precision");

                            b1.Property<string>("Theme")
                                .HasColumnType("text");

                            b1.HasKey("FormatId");

                            b1.ToTable("Formats");

                            b1.WithOwner()
                                .HasForeignKey("FormatId");
                        });

                    b.Navigation("Moderator");

                    b.Navigation("SelectionRules")
                        .IsRequired();
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsItem", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.NewsFeed", "Feed")
                        .WithMany("Items")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsPackage", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Announcement", null)
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.PodcastShow", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Format", null)
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ProgramSlot", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Format", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.StudioHistoryEntry", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Studio", "Studio")
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBitRendition", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.TalkBit", "TalkBit")
                        .WithMany("Renditions")
                        .HasForeignKey("TalkBitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalkBit");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkPart", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.TalkBreak", "TalkBreak")
                        .WithMany("Parts")
                        .HasForeignKey("TalkBreakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalkBreak");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Track", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Vote", b =>
                {
                    b.HasOne("WhipRadio.Core.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.Artist", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.ChatChannel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.NewsFeed", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBit", b =>
                {
                    b.Navigation("Renditions");
                });

            modelBuilder.Entity("WhipRadio.Core.Entities.TalkBreak", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
