using Microsoft.Extensions.DependencyInjection;
using WhipRadio.Core.Api;
using WhipRadio.Web.Components.Moderators;

namespace WhipRadio.Web.ComponentTests;

/// <summary>Direct tests for the components extracted from the Hosts page.</summary>
[TestClass]
public class ModeratorComponentsTests : BunitContext
{
    private static ModeratorDto Host(int id = 1, string name = "Maya") => new(
        id, name, name.ToLowerInvariant(), "en", "f", "qwen", "qv-maya", 1.0,
        Style: "late-night", PersonaPrompt: "warm host", PrefersVocals: null,
        PreferredGenres: "electronic", IsActive: true, IsAutoGenerated: false);

    [TestMethod]
    public void HireHostModal_RequiresAName_BeforeHiring()
    {
        this.RegisterConsoleServices(WebTestSupport.UnreachableOrchestrator());

        var modal = Render<HireHostModal>(parameters => parameters
            .Add(p => p.Visible, true)
            .Add(p => p.StationLanguage, "de"));

        Assert.Contains("de (station language)", modal.Markup);

        modal.FindAll("button").First(b => b.TextContent.Trim() == "Hire Host").Click();

        Assert.Contains("Name is required", modal.Markup);
    }

    [TestMethod]
    public void FireHostDialog_ShowsUsageImpact_AndHistory()
    {
        this.RegisterConsoleServices(WebTestSupport.UnreachableOrchestrator());
        var usage = new ModeratorUsageDto(
            IsNewsPresenter: true,
            IsWeatherSpecialist: false,
            AssignedFormatCount: 2,
            ActiveTalkBitCount: 0,
            PendingTalkBreakCount: 1,
            AssignedListenerMessageCount: 0,
            HistoricalAnnouncementCount: 5,
            HistoricalPlayCount: 1);

        var dialog = Render<FireHostDialog>(parameters => parameters
            .Add(p => p.Target, Host())
            .Add(p => p.Usage, usage));

        Assert.Contains("Fire", dialog.Markup);
        Assert.Contains("Maya", dialog.Markup);
        Assert.Contains("News presenter assignment", dialog.Markup);
        Assert.Contains("2 show format assignments", dialog.Markup);
        Assert.Contains("1 pending talk", dialog.Markup);
        Assert.Contains("History kept: 5 archived talks, 1 logged play.", dialog.Markup);
    }

    [TestMethod]
    public void FireHostDialog_ShowsCheckingState_WhileUsageLoads()
    {
        this.RegisterConsoleServices(WebTestSupport.UnreachableOrchestrator());

        var dialog = Render<FireHostDialog>(parameters => parameters
            .Add(p => p.Target, Host()));

        Assert.Contains("checking usage...", dialog.Markup);
    }

    [TestMethod]
    public void HostDetailPanel_RendersTagsAndFireButton()
    {
        this.RegisterConsoleServices(WebTestSupport.UnreachableOrchestrator());

        var panel = Render<HostDetailPanel>(parameters => parameters
            .Add(p => p.Host, Host()));

        Assert.Contains("Maya", panel.Markup);
        Assert.Contains("late-night", panel.Markup);
        Assert.Contains("on roster", panel.Markup);
        Assert.Contains("Fire", panel.Markup);
    }
}
