using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using WhipRadio.Core.Abstractions;
using WhipRadio.Core.Entities;
using WhipRadio.Core.Json;
using WhipRadio.Core.Personality;
using WhipRadio.Core.Slugs;
using WhipRadio.Infrastructure.Llm;
using WhipRadio.Infrastructure.Persistence;
using WhipRadio.Infrastructure.Tts;

namespace WhipRadio.Orchestrator.Services;

public enum SpecialistHostRole
{
    News,
    Weather,
}

public sealed class SpecialistHostCreationService(
    IDbContextFactory<RadioDbContext> dbFactory,
    ITextGenerationService llm,
    IVoiceDesignClient voiceDesigner,
    IProductionUpdatePublisher productionUpdates,
    ILogger<SpecialistHostCreationService> logger)
{
    public async Task<Moderator> CreateAsync(
        SpecialistHostRole role,
        string? hint,
        CancellationToken ct)
    {
        await using var db = await dbFactory.CreateDbContextAsync(ct);
        var settings = await db.StationSettings.AsNoTracking().GetStationSettingsOrDefaultAsync(ct);
        var existingNames = await db.Moderators.AsNoTracking()
            .Select(m => m.Name)
            .ToListAsync(ct);
        var existingSlugs = await db.Moderators.AsNoTracking()
            .Select(m => m.Slug)
            .ToListAsync(ct);

        var plan = await PlanAsync(role, settings, existingNames, hint, ct);
        var hintedName = ExtractNameFromHint(hint);
        var name = EnsureUniqueName(FirstNonEmpty(hintedName, Require(plan.Name, "name")), existingNames);
        var gender = NormalizeGender(FirstNonEmpty(ExtractGenderFromHint(hint), plan.Gender));
        var style = Require(plan.Style, "style");
        var persona = Require(plan.PersonaPrompt, "personaPrompt");
        var voiceDescription = Require(plan.VoiceDescription, "voiceDescription");
        var traits = ParseTraits(plan.Traits, role, style, plan.Talkativeness);

        var moderator = new Moderator
        {
            Name = name,
            Slug = SlugGenerator.UniqueFromName(name, existingSlugs),
            Language = StationLanguages.Normalize(settings.DefaultLanguage),
            Gender = gender,
            TtsEngine = TtsEngines.Qwen,
            Style = style,
            PersonaPrompt = persona,
            PreferredGenres = SanitizeOptional(plan.PreferredGenres, role == SpecialistHostRole.News
                ? "news,current events"
                : "weather,forecast"),
            Talkativeness = Math.Clamp(plan.Talkativeness ?? DefaultTalkativeness(role), 0, 1),
            BaselineEnergy = traits.Energy,
            BaselineFormality = traits.Formality,
            BaselineHumorLevel = traits.HumorLevel,
            BaselineTalkativeness = traits.Talkativeness,
            BaselineWarmth = traits.Warmth,
            IsNewsSpecialist = role == SpecialistHostRole.News,
            IsWeatherSpecialist = role == SpecialistHostRole.Weather,
            IsAutoGenerated = true,
            IsActive = true,
            SpeechRate = 1.0,
            VoiceDescription = voiceDescription,
        };
        ApplySpecialistTalkProfile(moderator, role);

        var voice = await voiceDesigner.DesignVoiceAsync(
            voiceDescription,
            moderator.Gender,
            moderator.Language,
            BuildVoiceIntroSample(moderator, role),
            ct);
        moderator.VoiceId = voice.Handle;

        db.Moderators.Add(moderator);
        await db.SaveChangesAsync(ct);

        var trackedSettings = await db.StationSettings.FindStationSettingsAsync(ct)
            ?? new StationSettings { Id = StationSettings.SingletonId };
        if (db.Entry(trackedSettings).State == EntityState.Detached)
        {
            db.StationSettings.Add(trackedSettings);
        }

        if (role == SpecialistHostRole.News)
        {
            trackedSettings.NewsPresenterModeratorId = moderator.Id;
        }
        else
        {
            trackedSettings.WeatherSpecialistModeratorId = moderator.Id;
        }

        await db.SaveChangesAsync(ct);
        await PublishAsync(role, ct);

        logger.LogInformation(
            "Program director created {Role} specialist {Name} with designed voice {VoiceId}",
            role,
            moderator.Name,
            moderator.VoiceId);
        return moderator;
    }

    private async Task<SpecialistHostPlan> PlanAsync(
        SpecialistHostRole role,
        StationSettings settings,
        IReadOnlyList<string> existingNames,
        string? hint,
        CancellationToken ct)
    {
        var prompt = BuildPrompt(role, settings, existingNames, hint);
        var systemPrompt =
            "You are WhipRadio's program director. Design radio hosts from station context. Return only valid JSON.";
        var jobLabel = $"Creating {role.ToString().ToLowerInvariant()} host";

        Exception? lastError = null;
        for (var attempt = 0; attempt < 2; attempt++)
        {
            var userPrompt = attempt == 0
                ? prompt
                : $"{prompt}\n\nPrevious reply rejected: {lastError?.Message}. Return only valid JSON matching the schema.";
            var raw = await llm.CompleteAsync(
                new TextGenerationRequest(systemPrompt, userPrompt, jobLabel, StructuredJson.SchemaFor<SpecialistHostPlan>(), "specialistHost"),
                ct);
            try
            {
                return ParsePlan(raw);
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                lastError = ex;
            }
        }

        throw new InvalidOperationException(
            $"Program director could not create a valid {role.ToString().ToLowerInvariant()} host profile: {lastError?.Message}");
    }

    private static string BuildPrompt(
        SpecialistHostRole role,
        StationSettings settings,
        IReadOnlyList<string> existingNames,
        string? hint)
        => PromptTemplates.Render("SpecialistHostPlanner", new Dictionary<string, string>
        {
            ["Role"] = role.ToString(),
            ["StationName"] = FirstNonEmpty(settings.StationName, "WhipRadio"),
            ["StationSlogan"] = FirstNonEmpty(settings.StationSlogan, "No slogan configured."),
            ["StationVision"] = FirstNonEmpty(settings.StationVision, "No station vision configured."),
            ["StationMission"] = FirstNonEmpty(settings.StationMission, "No station mission configured."),
            ["Language"] = StationLanguages.Normalize(settings.DefaultLanguage),
            ["Hint"] = FirstNonEmpty(hint, "No manual hint."),
            ["AvoidNames"] = existingNames.Count == 0
                ? "- none"
                : string.Join(Environment.NewLine, existingNames.OrderBy(name => name).Select(name => $"- {name}")),
        });

    private async Task PublishAsync(SpecialistHostRole role, CancellationToken ct)
    {
        if (role == SpecialistHostRole.News)
        {
            await productionUpdates.PublishNewsChangedAsync(ct);
        }
        else
        {
            await productionUpdates.PublishWeatherChangedAsync(ct);
        }
    }

    private static SpecialistHostPlan ParsePlan(string raw)
    {
        var result = StructuredJson.Parse<SpecialistHostPlan>(raw);
        var plan = result.IsValid
            ? result.Value!
            : throw new InvalidOperationException(result.Error ?? "JSON was empty.");

        _ = Require(plan.Name, "name");
        _ = Require(plan.Gender, "gender");
        _ = Require(plan.Style, "style");
        _ = Require(plan.PersonaPrompt, "personaPrompt");
        _ = Require(plan.VoiceDescription, "voiceDescription");
        return plan;
    }

    private static string EnsureUniqueName(string requestedName, IReadOnlyList<string> existingNames)
    {
        var used = existingNames.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var clean = requestedName.Trim();
        if (!used.Contains(clean))
        {
            return clean;
        }

        for (var suffix = 2; suffix < 1000; suffix++)
        {
            var candidate = $"{clean} {suffix}";
            if (!used.Contains(candidate))
            {
                return candidate;
            }
        }

        return $"{clean} {Guid.NewGuid():N}"[..Math.Min(48, clean.Length + 33)];
    }

    private static string NormalizeGender(string? gender)
    {
        var value = gender?.Trim().ToLowerInvariant();
        return value is "m" or "male" or "man"
            ? ModeratorGenders.Male
            : ModeratorGenders.Female;
    }

    private static string? ExtractNameFromHint(string? hint)
    {
        if (string.IsNullOrWhiteSpace(hint))
        {
            return null;
        }

        var normalized = Regex.Replace(hint, @"\s+", " ").Trim();
        foreach (var pattern in new[]
        {
            @"\b(?:named|called|name is)\s+(?<name>[A-Z][A-Za-z0-9'-]*(?:\s+[A-Z][A-Za-z0-9'-]*){0,3})",
            @"\b(?:female|male|woman|man)\s+(?:host|anchor|presenter|desk)?\s*(?:named|called)\s+(?<name>[A-Z][A-Za-z0-9'-]*(?:\s+[A-Z][A-Za-z0-9'-]*){0,3})",
        })
        {
            var match = Regex.Match(normalized, pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
            if (match.Success)
            {
                var candidate = match.Groups["name"].Value.Trim();
                return Regex.Replace(candidate, @"\s+", " ");
            }
        }

        return null;
    }

    private static string? ExtractGenderFromHint(string? hint)
    {
        if (string.IsNullOrWhiteSpace(hint))
        {
            return null;
        }

        var value = hint.Trim();
        if (Regex.IsMatch(value, @"\bfemale\b", RegexOptions.IgnoreCase))
        {
            return ModeratorGenders.Female;
        }

        if (Regex.IsMatch(value, @"\bmale\b", RegexOptions.IgnoreCase))
        {
            return ModeratorGenders.Male;
        }

        return null;
    }

    private static HostPersonalityTraits ParseTraits(
        SpecialistTraitPlan? traits,
        SpecialistHostRole role,
        string style,
        double? talkativeness)
    {
        var inferred = MoodEngine.InferBaseline(style, talkativeness ?? DefaultTalkativeness(role));
        if (traits is null)
        {
            return DefaultTraits(role, inferred);
        }

        return new HostPersonalityTraits(
            ParseTrait(traits.Energy, inferred.Energy),
            ParseTrait(traits.Formality, inferred.Formality),
            ParseTrait(traits.HumorLevel, role == SpecialistHostRole.News ? HumorLevel.VeryLow : HumorLevel.Low),
            ParseTrait(traits.Talkativeness, inferred.Talkativeness),
            ParseTrait(traits.Warmth, inferred.Warmth));
    }

    private static HostPersonalityTraits DefaultTraits(SpecialistHostRole role, HostPersonalityTraits inferred)
        => role == SpecialistHostRole.News
            ? new HostPersonalityTraits(
                inferred.Energy,
                Formality.Formal,
                HumorLevel.VeryLow,
                WhipRadio.Core.Personality.Talkativeness.Low,
                inferred.Warmth)
            : new HostPersonalityTraits(
                inferred.Energy,
                Formality.Formal,
                HumorLevel.Low,
                WhipRadio.Core.Personality.Talkativeness.Low,
                inferred.Warmth);

    private static T ParseTrait<T>(string? value, T fallback)
        where T : struct, Enum
        => Enum.TryParse<T>(value, ignoreCase: true, out var parsed) ? parsed : fallback;

    private static void ApplySpecialistTalkProfile(Moderator moderator, SpecialistHostRole role)
    {
        moderator.TalkBreakFrequencyTracks = 0;
        moderator.MinTalkPartsPerBreak = 1;
        moderator.MaxTalkPartsPerBreak = 1;
        moderator.AllowedTalkPartKinds = role == SpecialistHostRole.News
            ? "News,StationId,WeatherHandoff"
            : "Weather,StationId";
        moderator.ExactReplayTolerance = 1;
        moderator.EvergreenBitTolerance = 0.1;
    }

    private static string BuildVoiceIntroSample(Moderator moderator, SpecialistHostRole role)
        => role == SpecialistHostRole.News
            ? $"I'm {moderator.Name}. Here is the latest from the news desk."
            : $"I'm {moderator.Name}. Here is the local forecast.";

    private static double DefaultTalkativeness(SpecialistHostRole role)
        => role == SpecialistHostRole.News ? 0.3 : 0.25;

    private static string FirstNonEmpty(params string?[] values)
        => values.FirstOrDefault(value => !string.IsNullOrWhiteSpace(value))?.Trim() ?? string.Empty;

    private static string SanitizeOptional(string? value, string fallback)
        => string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();

    private static string Require(string? value, string field)
        => string.IsNullOrWhiteSpace(value)
            ? throw new InvalidOperationException($"Missing required field '{field}'.")
            : value.Trim();

    private sealed class SpecialistHostPlan
    {
        [JsonRequired]
        public string? Name { get; set; }

        [JsonRequired]
        public string? Gender { get; set; }

        [JsonRequired]
        public string? Style { get; set; }

        [JsonRequired]
        public string? PersonaPrompt { get; set; }

        public string? PreferredGenres { get; set; }

        public double? Talkativeness { get; set; }

        public SpecialistTraitPlan? Traits { get; set; }

        [JsonRequired]
        public string? VoiceDescription { get; set; }
    }

    private sealed class SpecialistTraitPlan
    {
        public string? Energy { get; set; }

        public string? Formality { get; set; }

        public string? HumorLevel { get; set; }

        public string? Talkativeness { get; set; }

        public string? Warmth { get; set; }
    }
}
