using System.Text;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using WhipRadio.Core.Abstractions;
using WhipRadio.Core.Conversations;
using WhipRadio.Core.Entities;
using WhipRadio.Core.Json;
using WhipRadio.Core.Speech;

namespace WhipRadio.Infrastructure.Llm;

/// <summary>
/// Multi-agent conversation engine (Phase 5, "Option B"): one light planning
/// call, then each turn is generated by the SPEAKING participant's own LLM call
/// with their persona, memory slices, and the running transcript. The
/// <see cref="ITurnTakingPolicy"/> decides who speaks; the budget math caps the
/// number of calls. Emits the exact same <see cref="ConversationTurn"/> records
/// as the single-call <see cref="ConversationScriptWriter"/>, which remains the
/// degradation fallback.
/// </summary>
public sealed class ConversationDirector(
    ITextGenerationService llm,
    ITurnTakingPolicy turnTakingPolicy,
    ILogger<ConversationDirector> logger)
{
    private const int TranscriptTailTurns = 12;
    private const int MaxConsecutiveTurnFailures = 2;

    // Cross-talk (Phase-0-Deferred §6): an interjection pulls this turn into the
    // previous speaker's tail. The previous turn must be long enough that a short
    // overlap reads as natural instead of clipping their point.
    private const int MinInterjectOverlapMs = 350;
    private const int MaxInterjectOverlapMs = 700;
    private const int MinInterjectableWords = 12;

    public async Task<ConversationScript> WriteAsync(
        ConversationScriptRequest request,
        IReadOnlyDictionary<string, IReadOnlyList<string>>? memorySlices,
        CancellationToken ct)
    {
        if (request.Speakers.Count < 2)
        {
            throw new InvalidOperationException("A conversation needs at least two speakers.");
        }

        var participants = request.Speakers
            .Select(speaker => new ConversationParticipant
            {
                SpeakerKey = speaker.SpeakerKey,
                DisplayName = speaker.DisplayName,
                ConversationRole = speaker.ConversationRole,
            })
            .ToList();
        var speakersByKey = request.Speakers.ToDictionary(speaker => speaker.SpeakerKey);
        var speakersByName = request.Speakers.ToDictionary(
            speaker => speaker.DisplayName.Trim(), speaker => speaker, StringComparer.OrdinalIgnoreCase);

        var (title, chapters) = await PlanEpisodeAsync(request, ct);

        var wordBudget = ConversationBudget.WordBudget(request.TargetDurationMinutes);
        var turnCap = ConversationBudget.TurnCap(request.TargetDurationMinutes, request.Speakers.Count);
        var turns = new List<ConversationTurn>();
        var wordsUsed = 0;
        var consecutiveFailures = 0;
        string? lastAddressedToKey = null;

        while (turns.Count < turnCap && wordsUsed < wordBudget)
        {
            var remainingWords = wordBudget - wordsUsed;
            // When the budget is nearly spent, hand the floor to the lead for a
            // natural sign-off instead of cutting someone off mid-thought.
            var closing = remainingWords <= 2 * ConversationBudget.AverageWordsPerTurn
                || turns.Count == turnCap - 1;
            var speakerKey = closing
                ? request.Speakers[0].SpeakerKey
                : turnTakingPolicy.NextSpeakerKey(new TurnTakingState(participants, turns, lastAddressedToKey));
            var speaker = speakersByKey[speakerKey];
            var chapter = CurrentChapter(chapters, turns.Count, turnCap);

            ConversationAgentTurnJson parsed;
            try
            {
                parsed = await GenerateTurnAsync(request, speaker, title, chapter, turns, speakersByKey, memorySlices, closing, ct);
                consecutiveFailures = 0;
            }
            catch (Exception ex) when (ex is not OperationCanceledException)
            {
                consecutiveFailures++;
                logger.LogWarning(
                    "Turn {Turn} by {Speaker} failed ({Failures}/{Max}): {Reason}",
                    turns.Count + 1, speaker.DisplayName, consecutiveFailures, MaxConsecutiveTurnFailures,
                    ex.GetBaseException().Message);
                if (consecutiveFailures >= MaxConsecutiveTurnFailures)
                {
                    throw new InvalidOperationException(
                        $"The conversation director gave up after {consecutiveFailures} consecutive turn failures: "
                        + ex.GetBaseException().Message);
                }

                continue;
            }

            var markers = SpeechMarkerNormalizer.Normalize(parsed.Text, allowBreath: true);
            var text = SpeechMarkerNormalizer.StripMarkers(parsed.Text).Trim();
            var previous = turns.Count > 0 ? turns[^1] : null;
            if (ShouldInterject(parsed.Interject, closing, previous))
            {
                previous!.PauseAfterMs = -Random.Shared.Next(MinInterjectOverlapMs, MaxInterjectOverlapMs + 1);
            }

            turns.Add(new ConversationTurn
            {
                SpeakerKey = speakerKey,
                Text = text,
                Markers = markers,
            });
            wordsUsed += CountWords(text);
            lastAddressedToKey = ResolveAddressedTo(parsed.AddressedTo, speakersByName, speakerKey);

            var wrapUp = parsed.WrapUp && speakerKey == request.Speakers[0].SpeakerKey;
            if (wrapUp || closing)
            {
                break;
            }
        }

        if (turns.Count < 2 || turns.Select(turn => turn.SpeakerKey).Distinct().Count() < 2)
        {
            throw new InvalidOperationException(
                "The conversation director produced fewer than two turns from two distinct speakers.");
        }

        var keyToName = request.Speakers.ToDictionary(speaker => speaker.SpeakerKey, speaker => speaker.DisplayName);
        var transcript = string.Join("\n\n", turns.Select(turn => $"{keyToName[turn.SpeakerKey]}: {turn.Text}"));
        logger.LogInformation(
            "Conversation \"{Title}\" directed: {Turns} turn(s), ~{Words} words (budget {Budget}, cap {Cap})",
            title, turns.Count, wordsUsed, wordBudget, turnCap);
        return new ConversationScript(title, turns, transcript);
    }

    private async Task<(string Title, IReadOnlyList<ConversationChapter> Chapters)> PlanEpisodeAsync(
        ConversationScriptRequest request,
        CancellationToken ct)
    {
        // Chaptered requests already carry their outline; only freeform episodes
        // get a light plan so the turns have somewhere to go.
        if (request.Structure == ConversationStructure.Chaptered && request.Chapters.Count > 0)
        {
            var providedTitle = string.IsNullOrWhiteSpace(request.Topic) ? "Untitled episode" : request.Topic;
            return (providedTitle, request.Chapters);
        }

        var roster = new StringBuilder();
        foreach (var speaker in request.Speakers)
        {
            roster.AppendLine($"- {speaker.DisplayName} ({speaker.ConversationRole}): {Truncate(speaker.PersonaBrief, 220)}");
        }

        var recentBlock = request.RecentEpisodeTitles.Count == 0
            ? "This is a fresh conversation; invent an angle that fits the brief."
            : "Invent a FRESH episode angle. Do not repeat these recent episodes:\n"
              + string.Join(Environment.NewLine, request.RecentEpisodeTitles.Select(title => $"- {title}"));

        var prompt = PromptTemplates.Render("ConversationDirector.Plan", new Dictionary<string, string>
        {
            ["StationName"] = request.StationName,
            ["KindLabel"] = request.Kind == ConversationKind.Podcast ? "podcast episode" : "studio talk",
            ["Topic"] = string.IsNullOrWhiteSpace(request.Topic) ? "The lead speaker's choice within the brief." : request.Topic,
            ["Brief"] = string.IsNullOrWhiteSpace(request.BriefWithKnowledge) ? "No additional brief." : request.BriefWithKnowledge,
            ["DurationMinutes"] = request.TargetDurationMinutes.ToString(),
            ["SpeakerRoster"] = roster.ToString().TrimEnd(),
            ["RecentEpisodesBlock"] = recentBlock,
        });

        var raw = await llm.CompleteAsync(
            new TextGenerationRequest(
                $"You are the producer of {request.StationName}. Return only valid JSON.",
                prompt,
                "Planning conversation episode",
                StructuredJson.SchemaFor<ConversationPlanJson>(),
                "conversationPlan"),
            ct);
        var result = StructuredJson.Parse<ConversationPlanJson>(raw);
        var plan = result.IsValid
            ? result.Value!
            : throw new InvalidOperationException($"Episode plan was not valid JSON: {result.Error}");
        if (string.IsNullOrWhiteSpace(plan.Title))
        {
            throw new InvalidOperationException("The episode plan is missing a title.");
        }

        var minutesPerChapter = Math.Max(
            1, request.TargetDurationMinutes / Math.Max(1, plan.Chapters.Count));
        var chapters = plan.Chapters
            .Where(chapter => !string.IsNullOrWhiteSpace(chapter.Title))
            .Take(4)
            .Select(chapter => new ConversationChapter
            {
                Title = chapter.Title.Trim(),
                Intent = (chapter.Intent ?? string.Empty).Trim(),
                TargetMinutes = minutesPerChapter,
            })
            .ToList();
        return (plan.Title.Trim(), chapters);
    }

    private async Task<ConversationAgentTurnJson> GenerateTurnAsync(
        ConversationScriptRequest request,
        ConversationSpeakerBrief speaker,
        string episodeTitle,
        ConversationChapter? chapter,
        IReadOnlyList<ConversationTurn> turns,
        IReadOnlyDictionary<string, ConversationSpeakerBrief> speakersByKey,
        IReadOnlyDictionary<string, IReadOnlyList<string>>? memorySlices,
        bool closing,
        CancellationToken ct)
    {
        var others = string.Join(
            Environment.NewLine,
            request.Speakers
                .Where(other => other.SpeakerKey != speaker.SpeakerKey)
                .Select(other => $"- {other.DisplayName} ({other.ConversationRole}): {Truncate(other.PersonaBrief, 160)}"));

        var tail = turns.Count == 0
            ? "(nothing yet — you open the conversation)"
            : string.Join(
                Environment.NewLine,
                turns.TakeLast(TranscriptTailTurns)
                    .Select(turn => $"{speakersByKey[turn.SpeakerKey].DisplayName}: {turn.Text}"));

        var memoryBlock = memorySlices is not null
            && memorySlices.TryGetValue(speaker.SpeakerKey, out var slices)
            && slices.Count > 0
                ? "Things you remember:\n" + string.Join(Environment.NewLine, slices.Select(slice => $"- {slice}"))
                : "";

        var guidance = closing
            ? "Bring the whole episode to a natural close now: a short wrap-up and sign-off. Set \"wrapUp\" to true."
            : turns.Count == 0
                ? "Open the conversation: greet naturally, set up the topic, and pull one of the other speakers in."
                : "Continue the conversation naturally.";

        var prompt = PromptTemplates.Render("ConversationDirector.Turn", new Dictionary<string, string>
        {
            ["SpeakerName"] = speaker.DisplayName,
            ["SpeakerRole"] = speaker.ConversationRole,
            ["KindLabel"] = request.Kind == ConversationKind.Podcast ? "podcast episode" : "studio talk",
            ["StationName"] = request.StationName,
            ["PersonaBrief"] = speaker.PersonaBrief,
            ["MemoryBlock"] = memoryBlock,
            ["EpisodeTitle"] = episodeTitle,
            ["Topic"] = request.Topic,
            ["Brief"] = string.IsNullOrWhiteSpace(request.BriefWithKnowledge) ? "No additional brief." : request.BriefWithKnowledge,
            ["ChapterIntent"] = chapter is null
                ? "One continuous conversation with a natural arc."
                : $"{chapter.Title} — {chapter.Intent}",
            ["OtherSpeakers"] = others,
            ["TranscriptTail"] = tail,
            ["TurnGuidance"] = guidance,
            ["Language"] = request.Language,
            ["TurnWordTarget"] = ConversationBudget.AverageWordsPerTurn.ToString(),
        });

        var raw = await llm.CompleteAsync(
            new TextGenerationRequest(
                $"You are {speaker.DisplayName}, a person in a radio conversation. Return only valid JSON.",
                prompt,
                $"Conversation turn: {speaker.DisplayName}",
                StructuredJson.SchemaFor<ConversationAgentTurnJson>(),
                "conversationTurn"),
            ct);
        var result = StructuredJson.Parse<ConversationAgentTurnJson>(raw);
        var parsed = result.IsValid
            ? result.Value!
            : throw new InvalidOperationException($"Turn was not valid JSON: {result.Error}");
        if (string.IsNullOrWhiteSpace(SpeechMarkerNormalizer.StripMarkers(parsed.Text)))
        {
            throw new InvalidOperationException($"{speaker.DisplayName} returned an empty turn.");
        }

        return parsed;
    }

    /// <summary>
    /// An interjection only lands when there is a previous turn to talk over,
    /// the episode is not signing off, and the previous turn is long enough
    /// (≥ <see cref="MinInterjectableWords"/> words) that a short overlap does
    /// not swallow its point. Exposed for tests.
    /// </summary>
    internal static bool ShouldInterject(bool interject, bool closing, ConversationTurn? previousTurn)
        => interject
            && !closing
            && previousTurn is not null
            && CountWords(previousTurn.Text) >= MinInterjectableWords;

    private static ConversationChapter? CurrentChapter(
        IReadOnlyList<ConversationChapter> chapters, int turnsSoFar, int turnCap)
    {
        if (chapters.Count == 0)
        {
            return null;
        }

        var index = Math.Min(chapters.Count - 1, turnsSoFar * chapters.Count / Math.Max(1, turnCap));
        return chapters[index];
    }

    private static string? ResolveAddressedTo(
        string? addressedTo,
        IReadOnlyDictionary<string, ConversationSpeakerBrief> speakersByName,
        string currentSpeakerKey)
    {
        if (string.IsNullOrWhiteSpace(addressedTo)
            || !speakersByName.TryGetValue(addressedTo.Trim(), out var target)
            || target.SpeakerKey == currentSpeakerKey)
        {
            return null;
        }

        return target.SpeakerKey;
    }

    private static int CountWords(string text)
        => text.Split([' ', '\r', '\n', '\t'], StringSplitOptions.RemoveEmptyEntries).Length;

    private static string Truncate(string value, int maxChars)
        => value.Length <= maxChars ? value : value[..maxChars].TrimEnd() + "...";

    internal sealed record ConversationPlanJson(
        [property: JsonRequired] string Title,
        [property: JsonRequired] IReadOnlyList<ConversationPlanChapterJson> Chapters);

    internal sealed record ConversationPlanChapterJson(
        [property: JsonRequired] string Title,
        string? Intent = null);

    internal sealed record ConversationAgentTurnJson(
        [property: JsonRequired] string Text,
        string? AddressedTo = null,
        bool WrapUp = false,
        bool Interject = false);
}
