using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using WhipRadio.Core.Abstractions;
using WhipRadio.Core.Api;
using WhipRadio.Core.Entities;
using WhipRadio.Core.News;
using WhipRadio.Core.Personality;
using WhipRadio.Core.Slugs;
using WhipRadio.Core.Playout;
using WhipRadio.Core.Selection;
using WhipRadio.Core.Speech;
using WhipRadio.Infrastructure.Llm;
using WhipRadio.Infrastructure.Music;
using WhipRadio.Infrastructure.Persistence;
using WhipRadio.Infrastructure.Studios;
using WhipRadio.Infrastructure.Tts;
using WhipRadio.Orchestrator.Configuration;
using WhipRadio.Orchestrator.Services;

namespace WhipRadio.Orchestrator.Api;

public static partial class RadioApiEndpoints
{
    public static IEndpointRouteBuilder MapRadioApi(this IEndpointRouteBuilder app)
    {
        var api = app.MapGroup("/api");

        MapNowPlaying(api);
        MapStationStatus(api);
        MapLibrary(api);
        MapArtistPosts(api);
        MapChat(api);
        MapAgentLog(api);
        MapPlayLog(api);
        MapTalkBreaks(api);
        MapVotes(api);
        MapModerators(api);
        MapSettings(api);
        MapProduction(api);
        MapConversations(api);
        MapBranding(api);
        MapFormatsAndSchedule(api);
        MapStats(api);
        MapConsole(api);
        MapPrivacy(api);

        return app;
    }

    private static string? NextOnAir(IEnumerable<ProgramSlot> slots, DateTimeOffset now)
    {
        var best = slots
            .Select(s =>
            {
                var daysAhead = ((s.DayOfWeek - (int)now.DayOfWeek) % 7 + 7) % 7;
                var start = now.Date.AddDays(daysAhead).AddMinutes(s.StartMinute);
                if (start < now.DateTime)
                {
                    start = start.AddDays(7);
                }

                return start;
            })
            .OrderBy(s => s)
            .Cast<DateTime?>()
            .FirstOrDefault();

        return best?.ToString("ddd HH:mm");
    }

    private static ArtistDto ToArtistDto(
        Artist artist,
        int trackCount,
        int upVotes,
        int downVotes,
        IReadOnlyList<ArtistMemberDto>? members = null)
        => new(
            artist.Id,
            artist.Name,
            artist.Slug,
            artist.Genre,
            artist.Subgenre,
            artist.StyleDescriptor,
            trackCount,
            upVotes,
            downVotes,
            artist.IsRetired,
            artist.Biography,
            artist.Type,
            artist.Origin,
            artist.FormationYear,
            artist.PromotionText,
            members,
            artist.Language);

    /// <summary>Transcript shown to listeners: the clean combined-run script when present,
    /// else the marked-up voiced text rendered to plain text (legacy rows).</summary>
    private static string? TranscriptOf(Announcement? announcement)
    {
        if (announcement is null)
        {
            return null;
        }

        return string.IsNullOrWhiteSpace(announcement.ScriptText)
            ? announcement.VoicedText is { } voiced ? SpeechMarkerNormalizer.ToPlainText(voiced) : null
            : announcement.ScriptText;
    }

    private static TrackDto ToDto(Track t, bool deletionPending = false) => new(
        t.Id, t.Title, t.Genre, t.Subgenre, t.Artist?.Name ?? "—", t.ArtistId, t.HasVocals,
        t.DurationSeconds, t.PlayCount, t.UpVotes, t.DownVotes, t.IsRetired, t.Backend, t.CreatedAt,
        t.Language, t.SongStory, t.Lyrics, t.TargetDurationSeconds, t.Style, deletionPending);

    private static TalkPartDto ToDto(TalkPart part)
        => new(
            part.SortOrder,
            part.Kind.ToString(),
            part.Purpose,
            part.Priority.ToString(),
            part.DesiredDurationSeconds,
            part.WordBudget);

    private static TalkBreakPriority ParseOnDemandPriority(string? value)
        => Enum.TryParse<TalkBreakPriority>(value, ignoreCase: true, out var parsed)
            && parsed == TalkBreakPriority.High
                ? TalkBreakPriority.High
                : TalkBreakPriority.Emergency;

    private static ModeratorDto ToDto(Moderator m, DateTimeOffset localNow) => new(
        m.Id, m.Name, m.Slug, m.Language, m.Gender, m.TtsEngine, m.VoiceId, m.SpeechRate, m.Style,
        m.PersonaPrompt, m.PrefersVocals, m.PreferredGenres, m.IsActive, m.IsAutoGenerated,
        m.Talkativeness, m.IsWeatherSpecialist, m.IsNewsSpecialist, m.PhotoUrl, ToDto(MoodEngine.Baseline(m)), ToDto(MoodEngine.Current(m, localNow)),
        ToDto(HostTalkProfile.FromModerator(m)));

    private static HostTalkProfileDto ToDto(HostTalkProfile profile)
        => new(
            profile.BreakFrequencyTracks,
            profile.MinPartsPerBreak,
            profile.MaxPartsPerBreak,
            string.Join(",", profile.AllowedKinds.OrderBy(kind => kind.ToString())),
            profile.ExactReplayTolerance,
            profile.EvergreenBitTolerance);

    private static async Task<ModeratorUsageDto> BuildModeratorUsageAsync(
        RadioDbContext db,
        int moderatorId,
        CancellationToken ct)
    {
        var settings = await db.StationSettings.AsNoTracking().GetStationSettingsOrDefaultAsync(ct);
        return new ModeratorUsageDto(
            settings.NewsPresenterModeratorId == moderatorId,
            settings.WeatherSpecialistModeratorId == moderatorId,
            await db.Formats.AsNoTracking().CountAsync(format => format.ModeratorId == moderatorId, ct),
            await db.TalkBits.AsNoTracking().CountAsync(bit => bit.ModeratorId == moderatorId
                && bit.Status == TalkBitStatus.Active, ct),
            await db.TalkBreaks.AsNoTracking().CountAsync(talkBreak => talkBreak.ModeratorId == moderatorId
                && (talkBreak.Status == TalkBreakStatus.Pending || talkBreak.Status == TalkBreakStatus.Rendered), ct),
            await db.ListenerMessages.AsNoTracking().CountAsync(message => message.ModeratorId == moderatorId
                && (message.Status == ListenerMessageStatus.Pending || message.Status == ListenerMessageStatus.Queued), ct),
            await db.Announcements.AsNoTracking().CountAsync(announcement => announcement.ModeratorId == moderatorId, ct),
            await db.PlayLog.AsNoTracking().CountAsync(entry => entry.ModeratorId == moderatorId, ct));
    }

    private static void ApplyTalkProfile(Moderator moderator, HostTalkProfileDto? profile)
    {
        if (profile is null)
        {
            return;
        }

        moderator.TalkBreakFrequencyTracks = Math.Max(0, profile.BreakFrequencyTracks);
        moderator.MinTalkPartsPerBreak = Math.Clamp(profile.MinPartsPerBreak, 0, 10);
        moderator.MaxTalkPartsPerBreak = Math.Clamp(
            Math.Max(profile.MaxPartsPerBreak, moderator.MinTalkPartsPerBreak),
            1,
            10);
        moderator.AllowedTalkPartKinds = string.IsNullOrWhiteSpace(profile.AllowedTalkPartKinds)
            ? new HostTalkProfileDto().AllowedTalkPartKinds
            : profile.AllowedTalkPartKinds;
        moderator.ExactReplayTolerance = Math.Max(0, profile.ExactReplayTolerance);
        moderator.EvergreenBitTolerance = Math.Clamp(profile.EvergreenBitTolerance, 0, 1);
    }

    private static ModeratorTraitsDto ToDto(HostPersonalityTraits traits)
        => new(
            traits.Energy.ToString(),
            traits.Formality.ToString(),
            traits.HumorLevel.ToString(),
            traits.Talkativeness.ToString(),
            traits.Warmth.ToString());

    private static HostPersonalityTraits ParseBaselineTraits(
        ModeratorTraitsDto? request,
        string style,
        double talkativeness)
    {
        var inferred = MoodEngine.InferBaseline(style, talkativeness);
        if (request is null)
        {
            return inferred;
        }

        return new HostPersonalityTraits(
            ParseTrait(request.Energy, inferred.Energy),
            ParseTrait(request.Formality, inferred.Formality),
            ParseTrait(request.HumorLevel, inferred.HumorLevel),
            ParseTrait(request.Talkativeness, inferred.Talkativeness),
            ParseTrait(request.Warmth, inferred.Warmth));
    }

    private static T ParseTrait<T>(string value, T fallback)
        where T : struct, Enum
        => Enum.TryParse<T>(value, ignoreCase: true, out var parsed) ? parsed : fallback;

    private static BrandingDto ToBrandingDto(StationSettings s, IReadOnlyList<Jingle> jingles) => new(
        s.StationName,
        s.StationSlogan,
        s.StationVision,
        s.StationMission,
        jingles.Select(ToDto).ToList());

    private static JingleDto ToDto(Jingle jingle) => new(
        jingle.Id,
        jingle.Label,
        jingle.Prompt,
        jingle.Style,
        jingle.Language,
        jingle.DurationSeconds,
        jingle.Backend,
        jingle.Status.ToString(),
        jingle.IsActive,
        jingle.CreatedAtUtc,
        jingle.LastUsedAtUtc,
        jingle.PlayCount,
        jingle.Kind.ToString());

    private static StationSettingsDto ToDto(StationSettings s) => new(
        s.StationName, s.StationSlogan, s.StationVision, s.StationMission,
        s.DefaultLanguage, s.TargetQueueLength, s.AnnouncementEveryNTracks,
        s.MusicProductionEnabled, s.PlayoutEnabled, s.MaxLibrarySize,
        s.MinTrackDurationSeconds, s.MaxTrackDurationSeconds, s.EnableBreathMarkers,
        s.FrequencyMhz, s.FirstDayOfWeek, MusicBackends.Normalize(s.DefaultMusicProvider),
        s.TextProvider, s.OpenAiApiKey, s.OpenAiModel,
        s.ElevenLabsEnabled, s.ElevenLabsApiKey, s.GreetingsEnabled,
        s.WeatherEnabled,
        WeatherScheduler.NormalizeCadence(s.WeatherCadenceMinutes),
        s.WeatherSpecialistModeratorId,
        s.WeatherFullHandoverEnabled,
        s.WeatherLocationName,
        s.WeatherLatitude,
        s.WeatherLongitude);

    private static NewsFeedDto ToDto(NewsFeed feed, int itemCount) => new(
        feed.Id,
        feed.Label,
        feed.Url,
        feed.Language,
        feed.Region,
        feed.Category,
        feed.IsEnabled,
        feed.IsSeeded,
        feed.PollCadenceMinutes,
        feed.MaxItemsPerPoll,
        feed.CreatedAtUtc,
        feed.LastPolledAtUtc,
        feed.LastError,
        itemCount);

    private static NewsPackageDto ToDto(NewsPackage package, string? transcript = null) => new(
        package.Id,
        package.Kind.ToString(),
        package.Status.ToString(),
        package.TargetUtc,
        package.TargetDurationSeconds,
        package.AnnouncementId,
        package.CreatedAtUtc,
        package.ProducedAtUtc,
        package.QueuedAtUtc,
        package.PlayedAtUtc,
        package.FailureReason,
        package.ProductionState,
        package.SourceSummary,
        package.StepIndex,
        package.StepTotal,
        transcript);

    private static WeatherProductionDto ToWeatherProductionDto(
        StationSettings settings,
        IReadOnlyCollection<Moderator> moderators) => new(
        settings.WeatherEnabled,
        WeatherScheduler.NormalizeCadence(settings.WeatherCadenceMinutes),
        settings.WeatherSpecialistModeratorId,
        settings.WeatherFullHandoverEnabled,
        settings.WeatherLocationName,
        settings.WeatherLatitude,
        settings.WeatherLongitude,
        BuildProductionWarning(settings, moderators));

    private static string? BuildProductionWarning(
        StationSettings settings,
        IReadOnlyCollection<Moderator> moderators)
        => ProductionSpecialistPolicy.BuildWarning(settings, moderators);

    private static bool TryNormalizeFeed(
        SaveNewsFeedDto request,
        out SaveNewsFeedDto normalized,
        out string? error)
    {
        normalized = request;
        error = null;
        if (string.IsNullOrWhiteSpace(request.Label))
        {
            error = "Feed label is required.";
            return false;
        }

        if (!Uri.TryCreate(request.Url, UriKind.Absolute, out var uri)
            || uri.Scheme is not ("http" or "https"))
        {
            error = "Feed URL must be an absolute HTTP or HTTPS URL.";
            return false;
        }

        normalized = request with
        {
            Label = request.Label.Trim(),
            Url = uri.ToString(),
            Language = string.IsNullOrWhiteSpace(request.Language) ? "en" : request.Language.Trim().ToLowerInvariant(),
            Region = string.IsNullOrWhiteSpace(request.Region) ? "global" : request.Region.Trim().ToLowerInvariant(),
            Category = string.IsNullOrWhiteSpace(request.Category) ? "general" : request.Category.Trim().ToLowerInvariant(),
            PollCadenceMinutes = Math.Clamp(request.PollCadenceMinutes, 5, 24 * 60),
            MaxItemsPerPoll = Math.Clamp(request.MaxItemsPerPoll, 1, 100),
        };
        return true;
    }

    private static string SanitizeOptional(string? value, string fallback)
        => string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();

    private static string HashClient(string value)
        => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)))[..16];
}
