namespace WhipRadio.Core.Api;

/// <summary>Wire contracts between the Orchestrator API/hub and the Web app.</summary>
public sealed record NowPlayingDto(
    string ItemType,
    Guid ItemId,
    string Title,
    DateTime StartedAtUtc,
    double DurationSeconds,
    string? ModeratorName,
    string? ArtistName = null,
    string? Transcript = null,
    int UpVotes = 0,
    int DownVotes = 0,
    string? FormatName = null);

public sealed record QueueItemDto(
    string ItemType,
    Guid ItemId,
    string Title,
    double DurationSeconds);

public sealed record TrackDto(
    Guid Id,
    string Title,
    string Genre,
    string Subgenre,
    string ArtistName,
    Guid? ArtistId,
    bool HasVocals,
    double DurationSeconds,
    int PlayCount,
    int UpVotes,
    int DownVotes,
    bool IsRetired,
    string Backend,
    DateTime CreatedAt);

public sealed record ArtistDto(
    Guid Id,
    string Name,
    string Genre,
    string Subgenre,
    string StyleDescriptor,
    int TrackCount,
    int UpVotes,
    int DownVotes,
    bool IsRetired);

public sealed record PlayLogEntryDto(
    DateTime PlayedAt,
    string ItemType,
    Guid ItemId,
    string Title,
    string? ModeratorName,
    double DurationSeconds,
    string? Transcript);

public sealed record ModeratorDto(
    int Id,
    string Name,
    string Language,
    string Gender,
    string TtsEngine,
    string VoiceId,
    double SpeechRate,
    string Style,
    string PersonaPrompt,
    bool? PrefersVocals,
    string PreferredGenres,
    bool IsActive,
    bool IsAutoGenerated,
    double Talkativeness = 0.5);

public sealed record CreateModeratorDto(
    string Name,
    string Language,
    string Gender,
    string TtsEngine,
    string Style,
    string PersonaPrompt,
    bool? PrefersVocals,
    string PreferredGenres,
    double Talkativeness = 0.5);

public sealed record StationSettingsDto(
    string StationName,
    string DefaultLanguage,
    int TargetQueueLength,
    int AnnouncementEveryNTracks,
    bool MusicProductionEnabled,
    bool PlayoutEnabled,
    int MaxLibrarySize,
    int MinTrackDurationSeconds,
    int MaxTrackDurationSeconds,
    bool EnableBreathMarkers,
    double FrequencyMhz,
    int FirstDayOfWeek,
    string TextProvider,
    string OpenAiApiKey,
    string OpenAiModel,
    bool ElevenLabsEnabled,
    string ElevenLabsApiKey,
    bool GreetingsEnabled = true);

public sealed record VoteRequestDto(Guid TrackId, int Direction);

public sealed record VoteResultDto(Guid TrackId, int UpVotes, int DownVotes, bool IsRetired);

public sealed record FormatDto(
    Guid Id,
    string Name,
    string Description,
    string Genre,
    string Subgenre,
    string? ModeratorName,
    int? ModeratorId,
    string Reason,
    bool IsEnabled,
    int UpVotes,
    int DownVotes,
    string? NextOnAir,
    double Talkativeness = 0.5);

public sealed record ProgramSlotDto(
    int Id,
    int DayOfWeek,
    int StartMinute,
    int DurationMinutes,
    Guid? FormatId,
    string? FormatName,
    string? ModeratorName,
    string? Genre);

public sealed record StatsDto(
    int CurrentListeners,
    int ListenerPeak,
    int TotalTracks,
    int TotalArtists,
    int TotalAnnouncements,
    int TotalPlays,
    int PlaysLastHour,
    int TotalVotes,
    double TotalMusicHours,
    IReadOnlyList<NameCountDto> TopArtists,
    IReadOnlyList<NameCountDto> HostAirtimeMinutes,
    IReadOnlyList<NameCountDto> TracksPerGenre);

public sealed record NameCountDto(string Name, double Value);

public sealed record ConsoleLineDto(DateTime TimestampUtc, string Level, string Category, string Message);

public sealed record GpuStatsDto(
    string Name,
    double UtilizationPercent,
    double MemoryUsedMb,
    double MemoryTotalMb,
    double TemperatureC);

public sealed record StorageAreaDto(string Name, double SizeMb, int FileCount);

public sealed record ServerStatsDto(
    string OsDescription,
    int ProcessorCount,
    double CpuUsagePercent,
    double MemoryTotalMb,
    double MemoryUsedMb,
    double ProcessMemoryMb,
    double ProcessUptimeSeconds,
    GpuStatsDto? Gpu,
    string DataRootPath,
    double DiskTotalGb,
    double DiskFreeGb,
    IReadOnlyList<StorageAreaDto> StorageAreas);

public sealed record SubmitGreetingDto(
    string SenderName,
    string MessageText,
    string Kind,
    string? RequestGenre = null,
    string? RequestMood = null);

public sealed record ListenerMessageDto(
    Guid Id,
    string SenderName,
    string MessageText,
    string Kind,
    string? RequestGenre,
    string? RequestMood,
    DateTime SubmittedAt,
    string Status,
    string? DismissalReason = null);
