namespace WhipRadio.Core.Entities;

public enum JingleStatus
{
    Ready,
    Failed,
    Retired,
}

public enum JingleKind
{
    /// <summary>A short sung/produced station ID, playable on air as gap fill.</summary>
    StationId,

    /// <summary>A loopable instrumental bed ducked under long news show speech.</summary>
    NewsBed,
}

/// <summary>A short station identity source generated by the music backend.</summary>
public class Jingle
{
    public Guid Id { get; set; }

    public JingleKind Kind { get; set; } = JingleKind.StationId;

    public string Label { get; set; } = string.Empty;

    public string Prompt { get; set; } = string.Empty;

    public string Style { get; set; } = string.Empty;

    public string Language { get; set; } = "en";

    public double DurationSeconds { get; set; }

    /// <summary>Relative to the /data root.</summary>
    public string FilePath { get; set; } = string.Empty;

    public string Backend { get; set; } = string.Empty;

    public string? ModelUsed { get; set; }

    public string? SeedUsed { get; set; }

    public string? TaskId { get; set; }

    public JingleStatus Status { get; set; } = JingleStatus.Ready;

    public bool IsActive { get; set; } = true;

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? LastUsedAtUtc { get; set; }

    public int PlayCount { get; set; }
}
