using WhipRadio.Core.Personality;

namespace WhipRadio.Core.Entities;

/// <summary>A radio host persona. Drives announcement style, TTS voice and track selection.</summary>
public class Moderator
{
    public int Id { get; set; }

    public string Name { get; set; } = string.Empty;

    /// <summary>BCP-47 language tag, e.g. "de", "en".</summary>
    public string Language { get; set; } = "en";

    /// <summary>"m" | "f" — must match the assigned TTS voice.</summary>
    public string Gender { get; set; } = "f";

    /// <summary>TTS engine key: "kokoro" | "piper" | "elevenlabs".</summary>
    public string TtsEngine { get; set; } = "kokoro";

    /// <summary>TTS voice key: a preset id ("af_heart") or a designed-voice
    /// handle ("qv-…") — engine-specific, stable across restarts.</summary>
    public string VoiceId { get; set; } = "af_heart";

    /// <summary>Free-text timbre/style description the voice was designed from
    /// (Qwen Voice-Design). Also conditions singing voices later (Phase 5).</summary>
    public string? VoiceDescription { get; set; }

    /// <summary>TTS speed multiplier, 0.7–1.3.</summary>
    public double SpeechRate { get; set; } = 1.0;

    /// <summary>System prompt fragment for the VoiceDirector stage.</summary>
    public string PersonaPrompt { get; set; } = string.Empty;

    /// <summary>E.g. "fast-energetic", "slow-thoughtful".</summary>
    public string Style { get; set; } = string.Empty;

    /// <summary>0–1: how chatty this host is between songs (0 = mostly music, 1 = loves to talk).</summary>
    public double Talkativeness { get; set; } = 0.5;

    public Energy BaselineEnergy { get; set; } = Energy.Medium;

    public Formality BaselineFormality { get; set; } = Formality.Balanced;

    public HumorLevel BaselineHumorLevel { get; set; } = HumorLevel.Medium;

    public WhipRadio.Core.Personality.Talkativeness BaselineTalkativeness { get; set; }
        = WhipRadio.Core.Personality.Talkativeness.Medium;

    public Warmth BaselineWarmth { get; set; } = Warmth.Medium;

    /// <summary>0 = no free talk; 1 = every gap may talk; 3 = roughly every third track.</summary>
    public int TalkBreakFrequencyTracks { get; set; } = 1;

    public int MinTalkPartsPerBreak { get; set; } = 1;

    public int MaxTalkPartsPerBreak { get; set; } = 3;

    /// <summary>CSV of AnnouncementKind values allowed until TalkPart gets its own model.</summary>
    public string AllowedTalkPartKinds { get; set; }
        = "SongIntro,SongOutro,Banter,PersonalNote,Joke,TalkBit,Jingle,ListenerGreeting,RequestDedication,StationId,Weather,HostChange";

    public int ExactReplayTolerance { get; set; } = 2;

    public double EvergreenBitTolerance { get; set; } = 0.5;

    /// <summary>null = no preference; drives track selection.</summary>
    public bool? PrefersVocals { get; set; }

    /// <summary>CSV genre list, e.g. "rock,indie".</summary>
    public string PreferredGenres { get; set; } = string.Empty;

    public bool IsWeatherSpecialist { get; set; }

    /// <summary>URL or app-relative path of the host's portrait; null = skeleton placeholder.</summary>
    public string? PhotoUrl { get; set; }

    public bool IsActive { get; set; } = true;

    /// <summary>True when the program director invented this host.</summary>
    public bool IsAutoGenerated { get; set; }
}

public static class ModeratorGenders
{
    public const string Male = "m";
    public const string Female = "f";
}
