namespace WhipRadio.Core.Entities;

/// <summary>
/// A song in the station's record collection — generated by a studio or
/// imported real music (see <see cref="TrackSource"/>).
/// </summary>
public class Track
{
    public Guid Id { get; set; }

    /// <summary>LLM-invented title.</summary>
    public string Title { get; set; } = string.Empty;

    public string Genre { get; set; } = string.Empty;

    /// <summary>E.g. "techno", "trance", "drum and bass" below the broad genre.</summary>
    public string Subgenre { get; set; } = string.Empty;

    public Guid? ArtistId { get; set; }

    public Artist? Artist { get; set; }

    /// <summary>Free-form prompt descriptor used at generation time.</summary>
    public string Style { get; set; } = string.Empty;

    /// <summary>Language the artist chose for this song, e.g. "en" or "es".</summary>
    public string Language { get; set; } = "en";

    /// <summary>musicgen ⇒ false, ace-step ⇒ true.</summary>
    public bool HasVocals { get; set; }

    /// <summary>Only for vocal tracks.</summary>
    public string? Lyrics { get; set; }

    /// <summary>Artist-written origin story: why and how this song was created.</summary>
    public string? SongStory { get; set; }

    /// <summary>Artist-planned target length before the backend renders the WAV.</summary>
    public int? TargetDurationSeconds { get; set; }

    /// <summary>Probed via ffprobe after generation.</summary>
    public double DurationSeconds { get; set; }

    /// <summary>
    /// Relative to the /data root for generated and uploaded tracks; absolute
    /// for <see cref="TrackSource.External"/> tracks whose file stays in its
    /// read-only external folder (resolve via MediaPaths.ResolveAbsolute).
    /// </summary>
    public string FilePath { get; set; } = string.Empty;

    /// <summary>Full prompt sent to the music backend.</summary>
    public string GenerationPrompt { get; set; } = string.Empty;

    /// <summary>"musicgen" | "ace-step"; imported tracks use "library".</summary>
    public string Backend { get; set; } = "musicgen";

    /// <summary>Where the audio came from; all import/deletion logic keys off this.</summary>
    public TrackSource Source { get; set; }

    /// <summary>SHA-256 of the audio file (imported tracks); dedupe key across sources.</summary>
    public string? FileHash { get; set; }

    /// <summary>File size at import time; rescans skip unchanged files cheaply.</summary>
    public long? FileSizeBytes { get; set; }

    /// <summary>File mtime (UTC) at import time; rescans skip unchanged files cheaply.</summary>
    public DateTime? FileModifiedUtc { get; set; }

    /// <summary>
    /// External file vanished at the last scan (drive offline, file moved).
    /// Selection skips missing files; the flag clears when the file returns.
    /// Kept apart from <see cref="IsRetired"/>, which stays vote/operator-owned.
    /// </summary>
    public bool FileMissing { get; set; }

    /// <summary>Display artist for imported real music; never a station <see cref="Artist"/>.</summary>
    public string? ImportedArtist { get; set; }

    /// <summary>Display album for imported real music.</summary>
    public string? ImportedAlbum { get; set; }

    /// <summary>Release year for imported real music.</summary>
    public int? ImportedYear { get; set; }

    /// <summary>Enrichment state; <see cref="MetadataStatus.None"/> for generated tracks.</summary>
    public MetadataStatus MetadataStatus { get; set; }

    /// <summary>Best match confidence (0..1) when matched.</summary>
    public double? MetadataConfidence { get; set; }

    /// <summary>Last enrichment attempt; failures retry after a cool-down.</summary>
    public DateTime? LastEnrichmentAttemptUtc { get; set; }

    public DateTime CreatedAt { get; set; }

    public int PlayCount { get; set; }

    public int UpVotes { get; set; }

    public int DownVotes { get; set; }

    /// <summary>Heavily disliked tracks stop rotating.</summary>
    public bool IsRetired { get; set; }
}
